
// Generated by https://quicktype.io// Generated by https://quicktype.io

export interface BlocResponse {
    content:          Bloc[];
    pageable:         string;
    totalPages:       number;
    totalElements:    number;
    last:             boolean;
    size:             number;
    number:           number;
    sort:             Sort;
    numberOfElements: number;
    first:            boolean;
    empty:            boolean;
}

export interface Bloc {
    id:              number;
    titulo:          string;
    contenido:       string;
    multimedia:      string;
    userImg:         string;
    userName:        string;
    listaDeUsuarios: ListaDeUsuario[];
}

export interface ListaDeUsuario {
    id:       string;
    username: string;
    email:    string;
    telefono: string;
    perfil:   string;
    rol:      string;
    avatar:   string;
}

export interface Sort {
    empty:    boolean;
    sorted:   boolean;
    unsorted: boolean;
}

