// Generated by https://quicktype.io

export interface LoginResponse {
    email:    string;
    username: string;
    avatar:   string;
    perfil:   string;
    role:     string;
    token:    string;
}

