// Generated by https://quicktype.io

export interface RegisterResponse {
    id:         string;
    username:   string;
    email:      string;
    telefono:   string;
    perfil:     string;
    rol:        string;
    avatar:     string;
    peticiones: any[];
    blocs:      any[];
}

